apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-even
  namespace: akshar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-even
  template:
    metadata:
      labels:
        app: client-even
    spec:
      containers:
        - name: client-even
          image: akshar-client-even
          imagePullPolicy: IfNotPresent
