apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: akshar
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
  type: ClusterIP
