apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: akshar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: akshar-server
          imagePullPolicy: IfNotPresent
